#cloud-config

##
## This is a etcd cloud-config for singal node
##

coreos:
    update:
        reboot-strategy: off
    etcd2:
        name: "%H"
        advertise-client-urls: https://$private_ipv4:2379
        initial-advertise-peer-urls: https://$private_ipv4:2380
        initial-cluster-state: new
        # runing a multi-node cluster with discovery mode:
        # generate a new token for each unique cluster from https://discovery.etcd.io/new
        # WARNING: replace each time you 'vagrant destroy'
        #discovery: https://discovery.etcd.io/<token>
        initial-cluster: "n1=https://172.17.8.101:2380,n2=https://172.17.8.102:2380,n3=https://172.17.8.103:2380"
        listen-client-urls: https://0.0.0.0:2379,https://0.0.0.0:4001
        listen-peer-urls: https://$private_ipv4:2380
    fleet:
        public-ip: $private_ipv4
        metadata: "platform=msd,role=etcd,host=%H"
        # see fleet issue https://github.com/coreos/fleet/issues/1106
        etcd-request-timeout: 15
# end
