############################################################
# Dockerfile to build OAuth2 provider Containers
# Based on xuwang/pyweb:latest
############################################################
FROM xuwang/pyweb:latest
MAINTAINER Xu Wang <xuwang@gmail.com>

# Add application code
ADD /application /application

# Expose ports
EXPOSE 443
